### ISSUE TITLE
Version 1.0.1 won't apply patches

### ISSUE THREAD

**Issue by martin-dzuro** [DoubleSymmetry/cocoapods-patch#17]
This one is quite odd. I'm using cocapods-patch in one of my project and until recently (version 0.0.9), everything was working fine. After upgrading to version 1.0.1, the patches are no longer applied. To rule out any interference from the project, I've created a brand new xcode project to test out the issue.

My current setup:

```
cocoapods (1.11.2)
cocoapods-core (1.11.2)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.4.0)
cocoapods-patch (1.0.1)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-trunk (1.5.0)
cocoapods-try (1.2.0)
```

Podfile is really simple: 

```
plugin 'cocoapods-patch'

target 'podTest' do
  use_frameworks!

  pod 'TestFairy'
end
```
with a very simple change in the Testfairy Pod ( patches/TestFairy+1.29.2.diff) :

```
diff --git a/cocoapods-patch-20211108-50631-2i5wvk/TestFairy/TestFairy.h b/Pods/TestFairy/TestFairy.h
index 5ef4a77..eae7b8d 100644
--- a/cocoapods-patch-20211108-50631-2i5wvk/TestFairy/TestFairy.h
+++ b/Pods/TestFairy/TestFairy.h
@@ -5,6 +5,7 @@
 
 @protocol TestFairySessionStateDelegate <NSObject>
 @optional
+-(void)testChange;
 /**
  * Callback when a session has successfully started on TestFairy.
  */

```

and yet, after pod install, the patch is not applied.

Going a bit deeper into the issue, I've noticed that _Pod::HooksManager.register('cocoapods-patch', :pre_integrate) do |context|_ never executes and the same goes for the _:after_integrate_ hook. The pre and post install hooks still work fine. What's also strange is the fact that the pre integrate hook works when defined in Podfile itself. 

Any ideas, what could be the cause of the issue?

**Comment by flexboxing** [comment]
Auto-applying patches on pod install is also not working for me on 1.0.1, but applying them manually from the command line still is

**Comment by fasci** [comment]
Same problem for me. Manually applying patches works, but auto-applying doesn't.

**Comment by dcvz** [comment]
Thanks for the report! We're looking into it now -- seems to be a change in the `CocoaPods` internals.

**Comment by dcvz** [comment]
For now we've released v1.0.2 that falls back to the previous way of applying patches while we try to get a fix merged in the main Cocoapods side.

**Comment by dcvz** [comment]
@martin-dzuro @fasci has the issue been resolved for you?

**Comment by fasci** [comment]
@dcvz Yes, this resolves the issue for me. Thanks a lot for the fix/rollback!

**Comment by martin-dzuro** [comment]
@dcvz it's working very nicely. I've tried it on a live project as well and it's applying the patches correctly. Thanks!
